
import React, { useState } from 'react';
import {
  View,
  Text,
  ScrollView,
  StyleSheet,
  Image,
  Pressable,
  StatusBar,
  Linking,
  Platform,
  Share,
  Alert,
} from 'react-native';
import { useTheme } from '../theme';

// Type matching the data passed from IdentifyScreen
export type AilmentPlantData = {
  plantName: string;
  scientificName: string;
  plantType?: string;
  medicinalBenefits: string; // semicolon separated or raw text
  sideEffects?: string;
  regionsFound?: string;
  preparation?: string;
  detailedExplanation?: string;
  source?: string;
};

// Navigation props
interface ScreenProps {
  route: any;
  navigation: any;
}

export default function AilmentDetailScreen({ route, navigation }: ScreenProps) {
  const { colors, dark } = useTheme();

  const { plantData } = route.params;
  const data = plantData as AilmentPlantData;
  const onBack = () => navigation.goBack();

  // Collapse states
  const [warningsOpen, setWarningsOpen] = useState(false);
  const [habitatOpen, setHabitatOpen] = useState(true); // Open by default for region info

  if (!data) return null;

  const plantName = data.plantName || 'Unknown Plant';
  const scientificName = data.scientificName || '';
  const plantType = data.plantType || 'Medicinal Plant';

  // Format Medicinal Benefits
  // Split by semicolon if present for list view, else just single item
  const medicinalUses = data.medicinalBenefits
    ? data.medicinalBenefits.split(';').map(u => u.trim()).filter(u => u.length > 0)
    : [];

  const sideEffects = data.sideEffects
    ? data.sideEffects.split(';').map(s => s.trim()).filter(s => s.length > 0)
    : [];

  // Extract URL from detailed explanation if present
  const sourceMatch = data.detailedExplanation?.match(/Source:\s*(https?:\/\/[^\s]+)/);
  const sourceUrl = sourceMatch ? sourceMatch[1] : null;
  const detailedText = sourceMatch
    ? data.detailedExplanation?.replace(/Source:\s*https?:\/\/[^\s]+/, '').trim()
    : data.detailedExplanation;

  // Handle Share/Download Report
  const handleShareReport = async () => {
    try {
      const reportText = `
══════════════════════════════════════
        MEDICINAL PLANT REPORT
══════════════════════════════════════

🌿 PLANT NAME: ${plantName}
📜 SCIENTIFIC NAME: ${scientificName}
🏷️ PLANT TYPE: ${plantType}

──────────────────────────────────────
        MEDICINAL USES
──────────────────────────────────────
${medicinalUses.map((use, i) => `${i + 1}. ${use}`).join('\n')}

──────────────────────────────────────
        DETAILED INFORMATION
──────────────────────────────────────
${detailedText || 'Not available'}

──────────────────────────────────────
        PREPARATION METHOD
──────────────────────────────────────
${data.preparation || 'Not specified'}

──────────────────────────────────────
        SIDE EFFECTS & CAUTIONS
──────────────────────────────────────
${sideEffects.length > 0 ? sideEffects.map(s => `• ${s}`).join('\n') : 'None reported'}

──────────────────────────────────────
        REGION FOUND
──────────────────────────────────────
${data.regionsFound || 'Unknown'}

──────────────────────────────────────
        REFERENCES
──────────────────────────────────────
${sourceUrl || 'Not available'}

══════════════════════════════════════
DISCLAIMER: This information is for educational purposes only. 
Always consult a healthcare professional before using any plant medicinally.
══════════════════════════════════════
Generated by MedPlant App
      `.trim();

      await Share.share({
        message: reportText,
        title: `${plantName} - Medicinal Plant Report`,
      });
    } catch (error: any) {
      Alert.alert('Share Failed', 'Unable to share the report. Please try again.');
    }
  };

  return (
    <View style={[styles.main, { backgroundColor: colors.background }]}>
      <StatusBar barStyle={dark ? 'light-content' : 'dark-content'} />

      {/* Top Section: Hero Placeholder (No Image for Ailment Search usually) & Back */}
      <View style={styles.imageContainer}>
        <View style={[styles.heroPlaceholder, { backgroundColor: colors.muted }]}>
          <Text style={{ fontSize: 80, opacity: 0.2 }}>🌿</Text>
        </View>

        <Pressable
          onPress={onBack}
          android_ripple={{ color: 'rgba(255,255,255,0.3)', borderless: true }}
          style={({ pressed }) => [
            styles.backButton,
            {
              backgroundColor: 'rgba(0,0,0,0.45)',
              opacity: Platform.OS === 'ios' && pressed ? 0.6 : 1
            }
          ]}
        >
          <Text style={styles.backButtonText}>←</Text>
        </Pressable>
      </View>

      <ScrollView
        style={styles.container}
        contentContainerStyle={styles.contentContainer}
        showsVerticalScrollIndicator={false}
      >
        {/* 1. Page Name & Header */}
        <View style={styles.header}>
          <Text style={[styles.pageName, { color: colors.primary }]}>Medicinal Plant Detail</Text>
          <View style={styles.titleRow}>
            <Text style={[styles.commonName, { color: colors.text }]}>
              {plantName}
            </Text>
            {/* Plant Type Badge */}
            <View style={[
              styles.confidenceBadge,
              { backgroundColor: colors.card, borderWidth: 1, borderColor: colors.border }
            ]}>
              <Text style={[styles.confidenceText, { color: colors.subtext }]}>
                {plantType}
              </Text>
            </View>
          </View>

          <Text style={[styles.scientificName, { color: colors.subtext }]}>
            {scientificName}
          </Text>
        </View>

        {/* 2. Medicinal Uses (PRIMARY SECTION) */}
        <View style={[styles.card, { backgroundColor: colors.card, borderColor: colors.primary, borderWidth: 2 }]}>
          <View style={styles.cardHeader}>
            <Text style={[styles.cardTitle, { color: colors.primary }]}>🌿 Medicinal Uses</Text>
          </View>
          <View style={styles.numberedList}>
            {medicinalUses.length > 0 ? (
              medicinalUses.map((item, i) => (
                <View key={i} style={styles.numberedItem}>
                  <Text style={[styles.number, { color: colors.primary }]}>{i + 1}.</Text>
                  <Text style={[styles.itemText, { color: colors.text }]}>{item}</Text>
                </View>
              ))
            ) : (
              <Text style={{ color: colors.subtext }}>No specific uses listed.</Text>
            )}
          </View>
        </View>

        {/* 3. Detailed Explanation (NEW SECTION FOR LONG PASSAGE) */}
        {detailedText && (
          <View style={[styles.card, { backgroundColor: colors.card, borderColor: colors.border }]}>
            <View style={styles.cardHeader}>
              <Text style={[styles.cardTitle, { color: colors.text }]}>📖 Detailed Information</Text>
            </View>
            <Text style={[styles.bodyText, { color: colors.text }]}>
              {detailedText}
            </Text>
          </View>
        )}

        {/* 4. Preparation (If available) */}
        {data.preparation && (
          <View style={[styles.card, { backgroundColor: colors.card, borderColor: colors.border }]}>
            <View style={styles.cardHeader}>
              <Text style={[styles.cardTitle, { color: colors.text }]}>🍵 Preparation Method</Text>
            </View>
            <Text style={[styles.itemText, { color: colors.text }]}>
              {data.preparation}
            </Text>
          </View>
        )}

        {/* 5. Side Effects */}
        {sideEffects.length > 0 && (
          <View style={[styles.card, { backgroundColor: colors.card, borderColor: colors.border }]}>
            <View style={styles.cardHeader}>
              <Text style={[styles.cardTitle, { color: colors.text }]}>💊 Known Side Effects</Text>
            </View>
            <View style={styles.bulletList}>
              {sideEffects.map((item, i) => (
                <View key={i} style={styles.bulletItem}>
                  <Text style={[styles.itemText, { color: colors.text }]}>• {item}</Text>
                </View>
              ))}
            </View>
          </View>
        )}

        {/* 6. Habitat & Distribution (Expandable) */}
        <Pressable
          onPress={() => setHabitatOpen(!habitatOpen)}
          android_ripple={{ color: colors.primary + '20' }}
          style={({ pressed }) => [
            styles.collapsibleHeader,
            {
              backgroundColor: colors.card,
              borderColor: colors.border,
              marginBottom: habitatOpen ? 0 : 28,
              opacity: Platform.OS === 'ios' && pressed ? 0.8 : 1
            }
          ]}
        >
          <Text style={[styles.collapsibleTitle, { color: colors.text }]}>📍 Habitat & Distribution</Text>
          <Text style={[styles.toggleIcon, { color: colors.text }]}>{habitatOpen ? '↑' : '↓'}</Text>
        </Pressable>

        {habitatOpen && (
          <View style={[styles.collapsibleContent, { backgroundColor: colors.card, borderColor: colors.border }]}>
            <Text style={[styles.habitatLabel, { color: colors.primary }]}>Region Found:</Text>
            <Text style={[styles.habitatText, { color: colors.subtext }]}>{data.regionsFound || 'Unknown'}</Text>
          </View>
        )}

        {/* 7. Research & References */}
        {sourceUrl && (
          <View style={styles.referencesCard}>
            <Text style={[styles.cardTitle, { color: colors.text, marginBottom: 12 }]}>📚 References</Text>
            <View style={styles.refItem}>
              <Text style={[styles.refText, { color: colors.primary }]} onPress={() => Linking.openURL(sourceUrl)}>
                🔗 {sourceUrl}
              </Text>
            </View>
          </View>
        )}

        {/* 8. Download/Share Report Button */}
        <Pressable
          onPress={handleShareReport}
          android_ripple={{ color: '#ffffff30', borderless: false }}
          style={({ pressed }) => [
            styles.downloadButton,
            {
              backgroundColor: colors.primary,
              opacity: Platform.OS === 'ios' && pressed ? 0.8 : 1
            }
          ]}
        >
          <Text style={styles.downloadButtonText}>📥  Download / Share Report</Text>
        </Pressable>

        {/* 9. Disclaimer */}
        <View style={styles.disclaimerContainer}>
          <Text style={[styles.disclaimerText, { color: colors.subtext }]}>
            MEDICAL DISCLAIMER: The information provided in this report is for educational purposes only and is not intended as medical advice. Always consult a qualified healthcare professional before using any plant for medicinal purposes.
          </Text>
        </View>

        {/* Bottom Padding */}
        <View style={{ height: 40 }} />

      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  main: {
    flex: 1,
  },
  imageContainer: {
    height: 280,
    width: '100%',
    position: 'relative',
  },
  heroImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  heroPlaceholder: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  backButton: {
    position: 'absolute',
    top: 50,
    left: 20,
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
  },
  backButtonText: {
    color: '#fff',
    fontSize: 22,
    fontWeight: '300',
  },
  container: {
    flex: 1,
    marginTop: -40,
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    backgroundColor: 'transparent',
  },
  contentContainer: {
    padding: 24,
    paddingBottom: 60,
  },
  header: {
    marginBottom: 28,
  },
  pageName: {
    fontSize: 14,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 1.5,
    marginBottom: 8,
  },
  titleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 6,
  },
  commonName: {
    fontSize: 32,
    fontWeight: '900',
    flex: 1,
  },
  scientificName: {
    fontSize: 16,
    fontStyle: 'italic',
    fontWeight: '500',
  },
  confidenceBadge: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    marginTop: 4,
    marginLeft: 12,
  },
  confidenceText: {
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  card: {
    borderRadius: 24,
    padding: 20,
    marginBottom: 28,
    borderWidth: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 12,
    elevation: 3,
  },
  cardHeader: {
    marginBottom: 16,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: '800',
  },
  numberedList: {
    gap: 12,
  },
  numberedItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  number: {
    fontSize: 16,
    fontWeight: '800',
    width: 28,
  },
  bulletList: {
    gap: 10,
  },
  bulletItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  itemText: {
    fontSize: 15,
    lineHeight: 24,
    flex: 1,
  },
  bodyText: {
    fontSize: 15,
    lineHeight: 24,
  },
  collapsibleHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 18,
    borderRadius: 16,
    borderWidth: 1,
  },
  collapsibleTitle: {
    fontSize: 18,
    fontWeight: '800',
  },
  toggleIcon: {
    fontSize: 18,
    fontWeight: '700',
  },
  collapsibleContent: {
    padding: 18,
    borderBottomLeftRadius: 16,
    borderBottomRightRadius: 16,
    borderWidth: 1,
    borderTopWidth: 0,
    marginTop: -2,
    marginBottom: 28,
  },
  habitatLabel: {
    fontSize: 14,
    fontWeight: '800',
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  habitatText: {
    fontSize: 15,
    lineHeight: 22,
  },
  referencesCard: {
    marginTop: 24,
    paddingHorizontal: 4,
    marginBottom: 20
  },
  refItem: {
    marginBottom: 10,
  },
  refText: {
    fontSize: 14,
    fontWeight: '600',
    textDecorationLine: 'underline',
  },
  disclaimerContainer: {
    marginTop: 20,
    paddingVertical: 20,
    borderTopWidth: 1,
    borderTopColor: '#eee',
  },
  disclaimerText: {
    fontSize: 11,
    lineHeight: 18,
    textAlign: 'center',
    fontStyle: 'italic',
  },
  downloadButton: {
    marginTop: 24,
    height: 56,
    borderRadius: 28,
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
  },
  downloadButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
});
